name: Snake CI/CD Pipeline

on:
  push:
    branches:
    - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Snake CICD
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v4

      -
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      -
        name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
  aws:
    needs: docker
    runs-on: ubuntu-latest
    environment: Snake CICD
    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      -
        name: Authenticate AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ secrets.AWS_REGION }}
      -
        name: Get Runner IP
        id: ip
        uses: haythem/public-ip@v1.3
      -
        name: Whitelist Runner IP
        run: |
          aws ec2 authorize-security-group-ingress \
          --group-id ${{ secrets.AWS_SECGRPID }} \
          --protocol tcp \
          --port 22 \
          --cidr ${{ steps.ip.outputs.ipv4 }}/32
      -
        name: Deploy to EC2
        run: |
          aws ec2-instance-connect ssh --instance-id ${{ secrets.AWS_EC2INSTANCEID }}
          docker stop webapp || true
          docker rm webapp || true
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
          docker run -d --name webapp -p 8080:8080 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
      -
        name: Revoke Runner IP Address
        if: ${{ always() }}
        run: |
          aws ec2 revoke-security-group-ingress \
          --group-id ${{ secrets.AWS_SECGRPID }} \
          --protocol tcp \
          --port 22 \
          --cidr ${{ steps.ip.outputs.ipv4 }}/32
